### ISSUE TITLE
An exception was encountered while deserializing response

### ISSUE THREAD

**Issue by nsahaytech** [sharp-bits/jmeter-amf#17]
I'm getting the following error while recording script using AMFProxyServer. I'm trying to evaluate JMETER to test FLEX application though not from a FLEX background

2011/11/10 12:28:53 ERROR - jmeter.protocol.amf.util.AmfXmlConverter: An exception was encountered while deserializing response.  java.lang.IndexOutOfBoundsException: Index: 50, Size: 2
    at java.util.ArrayList.RangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at flex.messaging.io.amf.Amf3Input.getStringReference(Amf3Input.java:718)
    at flex.messaging.io.amf.Amf3Input.readString(Amf3Input.java:244)
    at flex.messaging.io.amf.Amf3Input.readTraits(Amf3Input.java:548)
    at flex.messaging.io.amf.Amf3Input.readScriptObject(Amf3Input.java:402)
    at flex.messaging.io.amf.Amf3Input.readObjectValue(Amf3Input.java:152)
    at flex.messaging.io.amf.Amf3Input.readObject(Amf3Input.java:130)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:123)
    at flex.messaging.io.amf.Amf0Input.readArrayValue(Amf0Input.java:359)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:127)
    at flex.messaging.io.amf.Amf0Input.readObject(Amf0Input.java:94)
    at flex.messaging.io.amf.AmfMessageDeserializer.readObject(AmfMessageDeserializer.java:227)
    at flex.messaging.io.amf.AmfMessageDeserializer.readBody(AmfMessageDeserializer.java:206)
    at flex.messaging.io.amf.AmfMessageDeserializer.readMessage(AmfMessageDeserializer.java:126)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:168)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:140)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.populateSampler(AmfRequestHdr.java:463)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.getSampler(AmfRequestHdr.java:281)
    at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:229)

**Comment by sharp-bits** [comment]
What library are you using in your application? This seems to suggest that it is either not valid AMF3 data or the message sent from Flash is getting terminated before it is complete.

Since this is happening during a string read, it is also possible that there is an encoding difference between JMeter and the client/server. If you confirm this, you can change JMeter's default (or any JVM) by starting it with a command line option _-Dfile.encoding=UTF-8_.

**Comment by amandv** [comment]
still this error is reported with default encoding of Jmeter set to UTF-8

jmeter.protocol.amf.util.AmfXmlConverter: An exception was encountered while deserializing response.  flex.messaging.io.SerializationException: Class 'flex.messaging.io.amf.ASObject' must implement java.io.Externalizable to receive client IExternalizable instances.
    at flex.messaging.io.amf.Amf3Input.readExternalizable(Amf3Input.java:496)
    at flex.messaging.io.amf.Amf3Input.readScriptObject(Amf3Input.java:420)
    at flex.messaging.io.amf.Amf3Input.readObjectValue(Amf3Input.java:152)
    at flex.messaging.io.amf.Amf3Input.readObject(Amf3Input.java:130)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:123)
    at flex.messaging.io.amf.Amf0Input.readArrayValue(Amf0Input.java:359)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:127)
    at flex.messaging.io.amf.Amf0Input.readObject(Amf0Input.java:94)
    at flex.messaging.io.amf.AmfMessageDeserializer.readObject(AmfMessageDeserializer.java:227)
    at flex.messaging.io.amf.AmfMessageDeserializer.readBody(AmfMessageDeserializer.java:206)
    at flex.messaging.io.amf.AmfMessageDeserializer.readMessage(AmfMessageDeserializer.java:126)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:163)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.populateSampler(AmfRequestHdr.java:463)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.getSampler(AmfRequestHdr.java:281)
    at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:229)

2011/12/20 12:25:43 ERROR - jmeter.protocol.amf.util.AmfXmlConverter: An exception was encountered while deserializing response.  flex.messaging.io.SerializationException: Class 'flex.messaging.io.amf.ASObject' must implement java.io.Externalizable to receive client IExternalizable instances.
    at flex.messaging.io.amf.Amf3Input.readExternalizable(Amf3Input.java:496)
    at flex.messaging.io.amf.Amf3Input.readScriptObject(Amf3Input.java:420)
    at flex.messaging.io.amf.Amf3Input.readObjectValue(Amf3Input.java:152)
    at flex.messaging.io.amf.Amf3Input.readObject(Amf3Input.java:130)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:123)
    at flex.messaging.io.amf.Amf0Input.readArrayValue(Amf0Input.java:359)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:127)
    at flex.messaging.io.amf.Amf0Input.readObject(Amf0Input.java:94)
    at flex.messaging.io.amf.AmfMessageDeserializer.readObject(AmfMessageDeserializer.java:227)
    at flex.messaging.io.amf.AmfMessageDeserializer.readBody(AmfMessageDeserializer.java:206)
    at flex.messaging.io.amf.AmfMessageDeserializer.readMessage(AmfMessageDeserializer.java:126)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:163)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.populateSampler(AmfRequestHdr.java:463)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.getSampler(AmfRequestHdr.java:281)
    at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:229)

2011/12/20 12:25:58 ERROR - jmeter.protocol.amf.util.AmfXmlConverter: An exception was encountered while deserializing response.  flex.messaging.io.SerializationException: Class 'flex.messaging.io.amf.ASObject' must implement java.io.Externalizable to receive client IExternalizable instances.
    at flex.messaging.io.amf.Amf3Input.readExternalizable(Amf3Input.java:496)
    at flex.messaging.io.amf.Amf3Input.readScriptObject(Amf3Input.java:420)
    at flex.messaging.io.amf.Amf3Input.readObjectValue(Amf3Input.java:152)
    at flex.messaging.io.amf.Amf3Input.readObject(Amf3Input.java:130)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:123)
    at flex.messaging.io.amf.Amf0Input.readArrayValue(Amf0Input.java:359)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:127)
    at flex.messaging.io.amf.Amf0Input.readObject(Amf0Input.java:94)
    at flex.messaging.io.amf.AmfMessageDeserializer.readObject(AmfMessageDeserializer.java:227)
    at flex.messaging.io.amf.AmfMessageDeserializer.readBody(AmfMessageDeserializer.java:206)
    at flex.messaging.io.amf.AmfMessageDeserializer.readMessage(AmfMessageDeserializer.java:126)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:163)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.populateSampler(AmfRequestHdr.java:463)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.getSampler(AmfRequestHdr.java:281)
    at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:229)

**Comment by arm3n** [comment]
I am also running into the exception while deserializing a response.  I have set the encoding to UTF-8, have tried using blazeds-common and core versions 3.2.0.3978 and 4.0.0.14931.  Below is the exception in the log I am getting during the AMF Proxy Server recording:

2012/07/06 19:56:52 ERROR - jmeter.protocol.amf.util.AmfXmlConverter: An exception was encountered while deserializing response.  flex.messaging.io.SerializationException: Class 'flex.messaging.io.amf.ASObject' must implement java.io.Externalizable to receive client IExternalizable instances.
    at flex.messaging.io.amf.Amf3Input.readExternalizable(Amf3Input.java:496)
    at flex.messaging.io.amf.Amf3Input.readScriptObject(Amf3Input.java:420)
    at flex.messaging.io.amf.Amf3Input.readObjectValue(Amf3Input.java:152)
    at flex.messaging.io.amf.Amf3Input.readObject(Amf3Input.java:130)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:123)
    at flex.messaging.io.amf.Amf0Input.readArrayValue(Amf0Input.java:359)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:127)
    at flex.messaging.io.amf.Amf0Input.readObject(Amf0Input.java:94)
    at flex.messaging.io.amf.AmfMessageDeserializer.readObject(AmfMessageDeserializer.java:227)
    at flex.messaging.io.amf.AmfMessageDeserializer.readBody(AmfMessageDeserializer.java:206)
    at flex.messaging.io.amf.AmfMessageDeserializer.readMessage(AmfMessageDeserializer.java:126)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:168)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:140)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.populateSampler(AmfRequestHdr.java:463)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.getSampler(AmfRequestHdr.java:281)
    at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:224)

Any help would be much appreciated!

Thanks,
Armen

**Comment by arm3n** [comment]
I am also seeing this exception:

2012/07/06 20:11:16 ERROR - jmeter.protocol.amf.util.AmfXmlConverter: An exception was encountered while deserializing response.  java.lang.IndexOutOfBoundsException: Index: 58, Size: 2
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at flex.messaging.io.amf.Amf3Input.getStringReference(Amf3Input.java:718)
    at flex.messaging.io.amf.Amf3Input.readString(Amf3Input.java:244)
    at flex.messaging.io.amf.Amf3Input.readTraits(Amf3Input.java:548)
    at flex.messaging.io.amf.Amf3Input.readScriptObject(Amf3Input.java:402)
    at flex.messaging.io.amf.Amf3Input.readObjectValue(Amf3Input.java:152)
    at flex.messaging.io.amf.Amf3Input.readObject(Amf3Input.java:130)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:123)
    at flex.messaging.io.amf.Amf0Input.readArrayValue(Amf0Input.java:359)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:127)
    at flex.messaging.io.amf.Amf0Input.readObject(Amf0Input.java:94)
    at flex.messaging.io.amf.AmfMessageDeserializer.readObject(AmfMessageDeserializer.java:227)
    at flex.messaging.io.amf.AmfMessageDeserializer.readBody(AmfMessageDeserializer.java:206)
    at flex.messaging.io.amf.AmfMessageDeserializer.readMessage(AmfMessageDeserializer.java:126)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:168)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:140)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.populateSampler(AmfRequestHdr.java:463)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.getSampler(AmfRequestHdr.java:281)
    at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:224)

**Comment by djcald** [comment]
Hi, I also have this problem:

2012/08/09 09:36:26 INFO  - jmeter.util.JsseSSLManager: Using default SSL protocol: TLS 
2012/08/09 09:36:26 INFO  - jmeter.util.JsseSSLManager: SSL session context: per-thread 
2012/08/09 09:36:26 INFO  - jmeter.util.SSLManager: JmeterKeyStore Location:  type JKS 
2012/08/09 09:36:26 INFO  - jmeter.util.SSLManager: KeyStore created OK 
2012/08/09 09:36:26 WARN  - jmeter.util.SSLManager: Keystore file not found, loading empty keystore 
2012/08/09 09:36:27 INFO  - jmeter.protocol.amf.proxy.FormCharSetFinder: Using htmlparser version: 2.0 (Release Build Sep 17, 2006) 
2012/08/09 09:36:28 ERROR - jmeter.protocol.amf.util.AmfXmlConverter: An exception was encountered while deserializing response.  flex.messaging.io.SerializationException: Class 'flex.messaging.io.amf.ASObject' must implement java.io.Externalizable to receive client IExternalizable instances.
    at flex.messaging.io.amf.Amf3Input.readExternalizable(Amf3Input.java:496)
    at flex.messaging.io.amf.Amf3Input.readScriptObject(Amf3Input.java:420)
    at flex.messaging.io.amf.Amf3Input.readObjectValue(Amf3Input.java:152)
    at flex.messaging.io.amf.Amf3Input.readObject(Amf3Input.java:130)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:123)
    at flex.messaging.io.amf.Amf0Input.readArrayValue(Amf0Input.java:359)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:127)
    at flex.messaging.io.amf.Amf0Input.readObject(Amf0Input.java:94)
    at flex.messaging.io.amf.AmfMessageDeserializer.readObject(AmfMessageDeserializer.java:227)
    at flex.messaging.io.amf.AmfMessageDeserializer.readBody(AmfMessageDeserializer.java:206)
    at flex.messaging.io.amf.AmfMessageDeserializer.readMessage(AmfMessageDeserializer.java:126)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:168)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:140)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.populateSampler(AmfRequestHdr.java:463)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.getSampler(AmfRequestHdr.java:281)
    at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:224)

**Comment by weltraumpirat** [comment]
I have the same issue.  It seems like looking up my custom DTOs in the classpath works fine when recording AMF requests via the proxy, but somehow these dependencies are ignored when deserializing responses. 

Could that be related to the class registry problems that were mentioned in an earlier commit?  I really need a fix for this _yesterday_, so I'd gladly lend a hand in finding a solution - but it would be much easier if I had a short introduction in where the root of the problem is (my guess is it's class loading and scope?)...

**Comment by weltraumpirat** [comment]
Okay, changing a single line fixed the issue for me: In AmfRequest.java on line 263, it should say:

```
String amfResXml = AmfXmlConverter.convertAmfMessageToXml(res.getResponseData(),true);
```

Setting the second parameter to `true` caused the "missing classes" to be resolved correctly.  I could send a pull request, but since it's a single line, you might just want to change it yourself.

**Comment by djcald** [comment]
I'm using Jmeter. I've downloaded the jar files.
For that i need to get the sources right?

**Comment by weltraumpirat** [comment]
Right. Just fork the project, correct that line and compile via Ant.  All the project's dependencies are in jmeter/lib, resp. jmeter/lib/ext, so you shouldn't have any troubles setting up your IDE.

**Comment by djcald** [comment]
Is it possible to provide me the JMeter-AMF.jar with this change? I don't have the env prepared for java development.

**Comment by weltraumpirat** [comment]
For now, yes: https://github.com/weltraumpirat/jmeter-amf/downloads

**Comment by sharp-bits** [comment]
Fair warning, that option - useAliasRegistry - is set to false because it can cause additional exceptions when sampling with the proxy. It just comes down to how your application uses command messages.

**Comment by weltraumpirat** [comment]
So is AmfRequest used for both recording and playback of requests?  From my (quick and dirty) understanding of the mechanism, I was under the impression that it was used during the actual tests only...  Shouldn't we try to use inheritance to get us out of this mess (e.g. use ProxySamplingAmfRequest and SamplingAmfRequest to distinguish the two usages) and create a version of the plugin that works both ways?

**Comment by djcald** [comment]
Hi again!
Yes, my problem is when using the proxy. And it continues even with this new jmeter-AMF.jar file.
I have the exception and my application returns un error:

faultCode:Client.Error.MessageSend faultString:'Send failed' faultDetail:'Channel.Connect.Failed error Connect attempt timed out

and xml content is:

<ActionMessage>
  <version>3</version>
  <headers/>
  <bodies>
    <MessageBody>
      <targetURI>null</targetURI>
      <responseURI>/1</responseURI>
    </MessageBody>
  </bodies>
</ActionMessage>

Any ideia?

**Comment by weltraumpirat** [comment]
Have you included your custom classes in the jmeter classpath?

**Comment by sharp-bits** [comment]
At a glance it looks like you are correct and this will not negatively affect the amf->xml side. @djcald, try the patch and let us know how it goes.

**Comment by djcald** [comment]
on apache-jmeter-2.7\lib\ext i have:
-blazeds-common-4.0.0.14931.jar
-blazeds-core-4.0.0.14931.jar
-JMeter-AMF.jar --> patched version

and still have the same problem... this is an https site and i have this error on connection on browser and the exception on jmeter.

**Comment by weltraumpirat** [comment]
The custom DTO ("remote") classes you use in your application must be included in the classpath, as well.

**Comment by djcald** [comment]
Hi! On my application we are using BlazeDS jars now... We have updated the BlazeDS version to 4 and now the error is this:

2012/08/10 16:12:16 ERROR - jmeter.protocol.amf.util.AmfXmlConverter: An exception was encountered while deserializing response.  java.lang.IndexOutOfBoundsException: Index: 50, Size: 3
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at flex.messaging.io.amf.Amf3Input.getStringReference(Amf3Input.java:718)
    at flex.messaging.io.amf.Amf3Input.readString(Amf3Input.java:244)
    at flex.messaging.io.amf.Amf3Input.readTraits(Amf3Input.java:548)
    at flex.messaging.io.amf.Amf3Input.readScriptObject(Amf3Input.java:402)
    at flex.messaging.io.amf.Amf3Input.readObjectValue(Amf3Input.java:152)
    at flex.messaging.io.amf.Amf3Input.readObject(Amf3Input.java:130)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:123)
    at flex.messaging.io.amf.Amf0Input.readArrayValue(Amf0Input.java:359)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:127)
    at flex.messaging.io.amf.Amf0Input.readObject(Amf0Input.java:94)
    at flex.messaging.io.amf.AmfMessageDeserializer.readObject(AmfMessageDeserializer.java:227)
    at flex.messaging.io.amf.AmfMessageDeserializer.readBody(AmfMessageDeserializer.java:206)
    at flex.messaging.io.amf.AmfMessageDeserializer.readMessage(AmfMessageDeserializer.java:126)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:168)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:140)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.populateSampler(AmfRequestHdr.java:463)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.getSampler(AmfRequestHdr.java:281)
    at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:224)

2012/08/10 16:12:16 INFO  - jmeter.protocol.http.sampler.HTTPJavaImpl: Error Response Code: 404

**Comment by weltraumpirat** [comment]
I'm happy to report that I've been using the fixed version for both recording and playing back AMF tests for 4 days - without any problems whatsoever.  @djcald You obviously have some other configuration problems. See if the response you are getting is actually an AMF message - I get similar errors when the server returns an HTML error page (the response code 404 is an indicator that this might be the case).

**Comment by ers82** [comment]
Having the following issue need your help;

2013/07/17 13:25:58 INFO  - jmeter.protocol.amf.proxy.AmfDaemon: Proxy up and running! 
2013/07/17 13:26:02 ERROR - jmeter.protocol.amf.util.AmfXmlConverter: An exception was encountered while deserializing response.  flex.messaging.MessageException: Cannot create class of type 'Mflex.mes'. Type 'Mflex.mes' not found.
    at flex.messaging.util.ClassUtil.createClass(ClassUtil.java:66)
    at flex.messaging.io.AbstractProxy.getClassFromClassName(AbstractProxy.java:103)
    at flex.messaging.io.AbstractProxy.getClassFromClassName(AbstractProxy.java:85)
    at flex.messaging.io.AbstractProxy.createInstanceFromClassName(AbstractProxy.java:125)
    at flex.messaging.io.AbstractProxy.createInstance(AbstractProxy.java:148)
    at flex.messaging.io.amf.Amf3Input.readScriptObject(Amf3Input.java:437)
    at flex.messaging.io.amf.Amf3Input.readObjectValue(Amf3Input.java:153)
    at flex.messaging.io.amf.Amf3Input.readObject(Amf3Input.java:132)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:135)
    at flex.messaging.io.amf.Amf0Input.readArrayValue(Amf0Input.java:326)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:139)
    at flex.messaging.io.amf.Amf0Input.readObject(Amf0Input.java:95)
    at flex.messaging.io.amf.AmfMessageDeserializer.readObject(AmfMessageDeserializer.java:226)
    at flex.messaging.io.amf.AmfMessageDeserializer.readBody(AmfMessageDeserializer.java:205)
    at flex.messaging.io.amf.AmfMessageDeserializer.readMessage(AmfMessageDeserializer.java:125)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:168)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:140)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.populateSampler(AmfRequestHdr.java:463)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.getSampler(AmfRequestHdr.java:281)
    at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:224)

2013/07/17 13:26:07 INFO  - jmeter.protocol.amf.proxy.AmfDaemon: Proxy Server stopped

**Comment by weltraumpirat** [comment]
You are getting an AMF deserialization error that indicates a Class called "Mflex.mes" is missing. Since that is not a valid class name, I suppose there are errors in the message itself - perhaps missing quotes or escape characters? - or your custom DTO classes are not correctly included in the JAR. Either way: it's a configuration problem.

**Comment by mattrobbins** [comment]
I am getting this error when trying to capture my requests to my Flash application. Need Help as well.

2013/07/18 14:48:01 DEBUG - jmeter.protocol.amf.proxy.AmfProxy: Sampling AMF 
2013/07/18 14:48:01 DEBUG - jmeter.protocol.amf.proxy.AmfRequestHdr: Proxy: setting server: test.tqsapps.com 
2013/07/18 14:48:01 DEBUG - jmeter.protocol.amf.proxy.AmfRequestHdr: Proxy: setting method: POST 
2013/07/18 14:48:01 DEBUG - jmeter.protocol.amf.proxy.AmfRequestHdr: Proxy: setting port: 443 
2013/07/18 14:48:01 DEBUG - jmeter.protocol.amf.proxy.AmfRequestHdr: Proxy: setting protocol to : https 
2013/07/18 14:48:01 DEBUG - jmeter.protocol.amf.proxy.AmfRequestHdr: No encoding found, using JRE default encoding for request body 
2013/07/18 14:48:01 DEBUG - jmeter.protocol.amf.proxy.AmfRequestHdr: Proxy: setting path: /cASM_TST/messagebroker/amf 
2013/07/18 14:48:01 ERROR - jmeter.protocol.amf.util.AmfXmlConverter: An exception was encountered while deserializing response.  java.lang.IndexOutOfBoundsException: Index: 58, Size: 3
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at flex.messaging.io.amf.Amf3Input.getStringReference(Amf3Input.java:718)
    at flex.messaging.io.amf.Amf3Input.readString(Amf3Input.java:244)
    at flex.messaging.io.amf.Amf3Input.readTraits(Amf3Input.java:548)
    at flex.messaging.io.amf.Amf3Input.readScriptObject(Amf3Input.java:402)
    at flex.messaging.io.amf.Amf3Input.readObjectValue(Amf3Input.java:152)
    at flex.messaging.io.amf.Amf3Input.readObject(Amf3Input.java:130)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:123)
    at flex.messaging.io.amf.Amf0Input.readArrayValue(Amf0Input.java:359)
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:127)
    at flex.messaging.io.amf.Amf0Input.readObject(Amf0Input.java:94)
    at flex.messaging.io.amf.AmfMessageDeserializer.readObject(AmfMessageDeserializer.java:227)
    at flex.messaging.io.amf.AmfMessageDeserializer.readBody(AmfMessageDeserializer.java:206)
    at flex.messaging.io.amf.AmfMessageDeserializer.readMessage(AmfMessageDeserializer.java:126)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:168)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:140)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.populateSampler(AmfRequestHdr.java:463)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.getSampler(AmfRequestHdr.java:281)
    at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:224)

2013/07/18 14:48:01 DEBUG - jmeter.protocol.amf.proxy.AmfRequestHdr: sampler path = /cASM_TST/messagebroker/amf 
2013/07/18 14:48:01 DEBUG - jmeter.protocol.amf.proxy.AmfRequestHdr: getSampler: sampler path = /cASM_TST/messagebroker/amf 
2013/07/18 14:48:01 DEBUG - jmeter.protocol.amf.sampler.AmfRequest: Sampling https://test.tqsapps.com/cASM_TST/messagebroker/amf 
2013/07/18 14:48:01 DEBUG - jmeter.protocol.amf.sampler.AmfRequest: AMF Sample XML:

**Comment by mattrobbins** [comment]
Update on my Comment: I was able to fix this by adding this argument to the JVM in the .cmd file I put this before the "call jmeter" line.

set JVM_ARGS="-Dfile.encoding=ISO-8859-1"

My Application now comes up and I am able to capture the AMF requests.

**Comment by fahim786fahim** [comment]
Thanks Matt Robbins!!
It helped me a lot. BTW what does "-Dfile.encoding=ISO-8859-1" means?

**Comment by mattrobbins** [comment]
I am not 100% sure. I found this on some of the other issues and tried it.
I would guess it has something to do with how to interpret the messages.

**Comment by kurtxchen** [comment]
Hi All,

I have been trying this Jmeter-amf package for 2 weeks already, could you please help me and direct me what issue I have?

Thanks.
-Kurt.

2014/01/21 13:42:40 DEBUG - jmeter.protocol.amf.proxy.AmfProxy: Method CONNECT => SSL 
2014/01/21 13:42:40 DEBUG - jmeter.protocol.amf.proxy.AmfProxy: Start to negotiate SSL connection, host: dvantage.boarddemo.com 
2014/01/21 13:42:40 INFO  - jmeter.protocol.amf.proxy.AmfProxy: Opened Keystore file: /Users/chenk/Documents/Performance/apache-jmeter-2.10/bin/proxyserver.jks 
2014/01/21 13:42:40 ERROR - jmeter.protocol.amf.proxy.AmfProxy: Problem with SSL certificate? Ensure browser is set to accept the JMeter proxy cert: Keystore was tampered with, or password was incorrect 
2014/01/21 13:42:40 DEBUG - jmeter.protocol.amf.proxy.AmfProxy: Will deliver sample  
2014/01/21 13:42:40 DEBUG - jmeter.protocol.amf.proxy.AmfProxyControl: Sample excluded based on url (true) or content-type (false):  -

**Comment by mattrobbins** [comment]
Hi Kurt,

I think the problems lies with the version of jMeter you are using. I have the 2.9 r1437961 version. When I tried the 2.10 version I had the same error but haven't had time to figure out why that version didn't work. I would suggest trying the 2.9 version.

When I first started to record I got the same error. What I had to do to solve the problem was install the jmeter cert. IE should allow you do to do this. Try installing it different ways. You should be able to click on the HTTP:// and pick where you want to install the cert.

Also you do not need to change any settings on the AMF Proxy Server. I leave them at the default except I add some URL's I want to exclude. Everything else should be set to default. Also you want to make sure you have the same port 8888 (as shown in your pic) in the proxy setting in IE.

Hope this helps.

-Matt

**Comment by ke-chen** [comment]
Hi Matt,

Could you please provide the Jmeter-amf.jar download link?

Thanks.
-Kurt.

**Comment by mattrobbins** [comment]
I got the link from the same place you did so I am not sure what is causing you issue. 

When I get a chance u can send you what files I am using.

-Matt

On Wed, Jan 22, 2014 at 12:43 PM, ke-chen <notifications@github.com="mailto:notifications@github.com">> wrote:

Hi Matt,

Could you please provide the Jmeter-amf.jar download link?

Thanks.

-Kurt.

**Comment by kurtxchen** [comment]
Hi Matt,

I got the Jmeter-amf.jar from the above link 
https://github.com/steeltomato/jmeter-amf/issues/17#issuecomment-21606037

could you please provide the correct link for download the Jmeter-amf.jar file?

Thanks a bunch.
-Kurt

**Comment by kurtxchen** [comment]
sorry, this is the link:

https://github.com/weltraumpirat/jmeter-amf/downloads

**Comment by ke-chen** [comment]
The only diff, I have mac machine here.

Thanks.
-Kurt.

**Comment by ke-chen** [comment]
Hi Matt,

I think our only diff is that I am using Mac machine, with Firefox browser.

I have seen some screen shot, other people posted online which shows the AMF proxy server has AMF type,
for my AMF proxy server only have httpclient4 and httpclient3.1 and java type, never seen AMF type,  do you
have AMF on your AMF proxy server GUI?

Thanks.
-Kurt.

**Comment by ke-chen** [comment]
When I go to Bank of America site, I got this from Browser, please help me out here? 

thanks a lot.
-Kurt.

javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Certificates does not conform to algorithm constraints
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1884)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:276)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:270)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1341)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:153)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:804)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1016)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
    at org.apache.jmeter.protocol.http.sampler.HTTPJavaImpl.sample(HTTPJavaImpl.java:487)
    at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:62)
    at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1088)
    at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:255)
Caused by: java.security.cert.CertificateException: Certificates does not conform to algorithm constraints
    at sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:946)
    at sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:872)
    at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:814)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1323)
    ... 14 more
