### ISSUE TITLE
Support for Jmeter 2.6 : Could not instantiate org.apache.jmeter.protocol.amf.gui.AmfRequestGui 

### ISSUE THREAD

**Issue by mordechai** [sharp-bits/jmeter-amf#23]
Cannot use GUI with plugin in Jmeter 2.6.  Clicking on any menu within Jmeter GUI generates exceptions and does not work.

Following exceptions shown:

Uncaught execption java.lang.NoClassDefFoundError: could not initialize class org.apache.jmeter.gui.util.MenuFactory

2012/03/06 12:47:18 INFO  - jmeter.gui.action.LookAndFeelCommand: Using look and feel: javax.swing.plaf.metal.MetalLookAndFeel [Metal, CrossPlatform] 
2012/03/06 12:47:18 INFO  - jmeter.util.BSFTestElement: Registering JMeter version of JavaScript engine as work-round for BSF-22 
2012/03/06 12:47:19 WARN  - jmeter.gui.util.MenuFactory: Could not instantiate org.apache.jmeter.protocol.amf.gui.AmfRequestGui java.lang.NoSuchMethodError: org.apache.jmeter.protocol.http.config.gui.UrlConfigGui.<init>(ZZ)V
    at org.apache.jmeter.protocol.amf.gui.AmfRequestGui.init(AmfRequestGui.java:97)
    at org.apache.jmeter.protocol.amf.gui.AmfRequestGui.<init>(AmfRequestGui.java:69)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at org.apache.jmeter.gui.util.MenuFactory.initializeMenus(MenuFactory.java:455)
    at org.apache.jmeter.gui.util.MenuFactory.<clinit>(MenuFactory.java:159)
    at org.apache.jmeter.control.gui.WorkBenchGui.createPopupMenu(WorkBenchGui.java:86)
    at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:158)
    at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:46)
    at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:80)
    at org.apache.jmeter.gui.action.ActionRouter.access$000(ActionRouter.java:41)
    at org.apache.jmeter.gui.action.ActionRouter$1.run(ActionRouter.java:62)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

2012/03/06 12:47:19 ERROR - jmeter.gui.util.MenuFactory:  java.lang.NoSuchMethodError: org.apache.jmeter.protocol.http.config.gui.UrlConfigGui.<init>(ZZ)V
    at org.apache.jmeter.protocol.amf.gui.AmfRequestGui.init(AmfRequestGui.java:97)
    at org.apache.jmeter.protocol.amf.gui.AmfRequestGui.<init>(AmfRequestGui.java:69)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at org.apache.jmeter.gui.util.MenuFactory.initializeMenus(MenuFactory.java:455)
    at org.apache.jmeter.gui.util.MenuFactory.<clinit>(MenuFactory.java:159)
    at org.apache.jmeter.control.gui.WorkBenchGui.createPopupMenu(WorkBenchGui.java:86)
    at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:158)
    at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:46)
    at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:80)
    at org.apache.jmeter.gui.action.ActionRouter.access$000(ActionRouter.java:41)
    at org.apache.jmeter.gui.action.ActionRouter$1.run(ActionRouter.java:62)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

2012/03/06 12:47:19 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoSuchMethodError: org.apache.jmeter.protocol.http.config.gui.UrlConfigGui.<init>(ZZ)V
    at org.apache.jmeter.protocol.amf.gui.AmfRequestGui.init(AmfRequestGui.java:97)
    at org.apache.jmeter.protocol.amf.gui.AmfRequestGui.<init>(AmfRequestGui.java:69)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at org.apache.jmeter.gui.util.MenuFactory.initializeMenus(MenuFactory.java:455)
    at org.apache.jmeter.gui.util.MenuFactory.<clinit>(MenuFactory.java:159)
    at org.apache.jmeter.control.gui.WorkBenchGui.createPopupMenu(WorkBenchGui.java:86)
    at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:158)
    at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:46)
    at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:80)
    at org.apache.jmeter.gui.action.ActionRouter.access$000(ActionRouter.java:41)
    at org.apache.jmeter.gui.action.ActionRouter$1.run(ActionRouter.java:62)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

2012/03/06 12:47:24 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: Could not initialize class org.apache.jmeter.gui.util.MenuFactory
    at org.apache.jmeter.control.gui.WorkBenchGui.createPopupMenu(WorkBenchGui.java:86)
    at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:158)
    at org.apache.jmeter.gui.tree.JMeterTreeListener.displayPopUp(JMeterTreeListener.java:312)
    at org.apache.jmeter.gui.tree.JMeterTreeListener.mousePressed(JMeterTreeListener.java:258)
    at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$2.run(Unknown Source)
    at java.awt.EventQueue$2.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by alagirisamys** [comment]
I have the same error. The right click button isnt working when i use this API. This project would be a great one if this error is somehow removed!

2012/03/28 16:38:47 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoSuchMethodError: org.apache.jmeter.protocol.http.config.gui.UrlConfigGui.<init>(ZZ)V
    at org.apache.jmeter.protocol.amf.gui.AmfRequestGui.init(AmfRequestGui.java:97)
    at org.apache.jmeter.protocol.amf.gui.AmfRequestGui.<init>(AmfRequestGui.java:69)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at org.apache.jmeter.gui.util.MenuFactory.initializeMenus(MenuFactory.java:455)
    at org.apache.jmeter.gui.util.MenuFactory.<clinit>(MenuFactory.java:159)
    at org.apache.jmeter.control.gui.WorkBenchGui.createPopupMenu(WorkBenchGui.java:86)
    at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:158)
    at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:46)
    at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:80)
    at org.apache.jmeter.gui.action.ActionRouter.access$000(ActionRouter.java:41)
    at org.apache.jmeter.gui.action.ActionRouter$1.run(ActionRouter.java:62)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:597)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:273)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:183)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:173)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:168)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:160)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:121)

**Comment by alagirisamys** [comment]
2012/03/28 16:38:46 INFO  - jmeter.util.JMeterUtils: Setting Locale to en_US 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: Loading user properties from: C:\Softwares\JmeterPlugin\apache-jmeter-2.6\bin\user.properties 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: Loading system properties from: C:\Softwares\JmeterPlugin\apache-jmeter-2.6\bin\system.properties 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: Copyright (c) 1998-2012 The Apache Software Foundation 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: Version 2.6 r1237317 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: java.version=1.6.0 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: java.vm.name=Java HotSpot(TM) Client VM 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: os.name=Windows Vista 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: os.arch=x86 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: os.version=6.1 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: file.encoding=Cp1252 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: Default Locale=English (United States) 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: JMeter  Locale=English (United States) 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: JMeterHome=C:\Softwares\JmeterPlugin\apache-jmeter-2.6 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: user.dir  =C:\Softwares\JmeterPlugin\apache-jmeter-2.6\bin 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: PWD       =C:\Softwares\JmeterPlugin\apache-jmeter-2.6\bin 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: IP: 192.168.1.5 Name: Alagiri-PC FullName: Alagiri-PC 
2012/03/28 16:38:46 INFO  - jmeter.JMeter: Loaded icon properties from org/apache/jmeter/images/icon.properties 
2012/03/28 16:38:47 INFO  - jmeter.engine.util.CompoundVariable: Note: Function class names must contain the string: '.functions.' 
2012/03/28 16:38:47 INFO  - jmeter.engine.util.CompoundVariable: Note: Function class names must not contain the string: '.gui.' 
2012/03/28 16:38:47 INFO  - jmeter.gui.action.LookAndFeelCommand: Using look and feel: javax.swing.plaf.metal.MetalLookAndFeel [Metal, CrossPlatform] 
2012/03/28 16:38:47 INFO  - jmeter.util.BSFTestElement: Registering JMeter version of JavaScript engine as work-round for BSF-22 
2012/03/28 16:38:47 WARN  - jmeter.gui.util.MenuFactory: Could not instantiate org.apache.jmeter.protocol.amf.gui.AmfRequestGui java.lang.NoSuchMethodError: org.apache.jmeter.protocol.http.config.gui.UrlConfigGui.<init>(ZZ)V
    at org.apache.jmeter.protocol.amf.gui.AmfRequestGui.init(AmfRequestGui.java:97)
    at org.apache.jmeter.protocol.amf.gui.AmfRequestGui.<init>(AmfRequestGui.java:69)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at org.apache.jmeter.gui.util.MenuFactory.initializeMenus(MenuFactory.java:455)
    at org.apache.jmeter.gui.util.MenuFactory.<clinit>(MenuFactory.java:159)
    at org.apache.jmeter.control.gui.WorkBenchGui.createPopupMenu(WorkBenchGui.java:86)
    at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:158)
    at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:46)
    at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:80)
    at org.apache.jmeter.gui.action.ActionRouter.access$000(ActionRouter.java:41)
    at org.apache.jmeter.gui.action.ActionRouter$1.run(ActionRouter.java:62)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:597)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:273)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:183)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:173)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:168)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:160)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:121)

2012/03/28 16:38:47 ERROR - jmeter.gui.util.MenuFactory:  java.lang.NoSuchMethodError: org.apache.jmeter.protocol.http.config.gui.UrlConfigGui.<init>(ZZ)V
    at org.apache.jmeter.protocol.amf.gui.AmfRequestGui.init(AmfRequestGui.java:97)
    at org.apache.jmeter.protocol.amf.gui.AmfRequestGui.<init>(AmfRequestGui.java:69)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at org.apache.jmeter.gui.util.MenuFactory.initializeMenus(MenuFactory.java:455)
    at org.apache.jmeter.gui.util.MenuFactory.<clinit>(MenuFactory.java:159)
    at org.apache.jmeter.control.gui.WorkBenchGui.createPopupMenu(WorkBenchGui.java:86)
    at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:158)
    at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:46)
    at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:80)
    at org.apache.jmeter.gui.action.ActionRouter.access$000(ActionRouter.java:41)
    at org.apache.jmeter.gui.action.ActionRouter$1.run(ActionRouter.java:62)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:597)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:273)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:183)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:173)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:168)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:160)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:121)

2012/03/28 16:38:47 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoSuchMethodError: org.apache.jmeter.protocol.http.config.gui.UrlConfigGui.<init>(ZZ)V
    at org.apache.jmeter.protocol.amf.gui.AmfRequestGui.init(AmfRequestGui.java:97)
    at org.apache.jmeter.protocol.amf.gui.AmfRequestGui.<init>(AmfRequestGui.java:69)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at org.apache.jmeter.gui.util.MenuFactory.initializeMenus(MenuFactory.java:455)
    at org.apache.jmeter.gui.util.MenuFactory.<clinit>(MenuFactory.java:159)
    at org.apache.jmeter.control.gui.WorkBenchGui.createPopupMenu(WorkBenchGui.java:86)
    at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:158)
    at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:46)
    at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:80)
    at org.apache.jmeter.gui.action.ActionRouter.access$000(ActionRouter.java:41)
    at org.apache.jmeter.gui.action.ActionRouter$1.run(ActionRouter.java:62)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:597)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:273)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:183)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:173)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:168)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:160)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:121)

**Comment by kokeszko** [comment]
i have this addon in JMeter 2.11 r1554548 (which is pretty fresh) and no exception appears but can't  choose type: AMF from HTTP Sampler settings
