### ISSUE TITLE
UnknownTypeException while deserializing amf response

### ISSUE THREAD

**Issue by RaphaelMui** [sharp-bits/jmeter-amf#25]
I got an exception while deserializing amf response.

ERROR - jmeter.protocol.amf.util.AmfXmlConverter: An exception was encountered while deserializing response.  flex.messaging.io.UnknownTypeException: Unknown AMF type '-3'.
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:214)
    at flex.messaging.io.amf.Amf0Input.readObject(Amf0Input.java:94)
    at flex.messaging.io.amf.AmfMessageDeserializer.readObject(AmfMessageDeserializer.java:227)
    at flex.messaging.io.amf.AmfMessageDeserializer.readBody(AmfMessageDeserializer.java:206)
    at flex.messaging.io.amf.AmfMessageDeserializer.readMessage(AmfMessageDeserializer.java:126)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:168)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:140)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.populateSampler(AmfRequestHdr.java:463)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.getSampler(AmfRequestHdr.java:281)
    at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:229)

I am using GraniteDS, jmeter 2.5.1 + blazeds-core-4.0.0.14931.

**Comment by RaphaelMui** [comment]
I guess that I'm having the same problem as described in issue#18.

**Comment by kurtxchen** [comment]
jmeter.protocol.amf.util.AmfXmlConverter: An exception was encountered while deserializing response.  flex.messaging.io.UnknownTypeException: Unknown AMF type '-65'.

**Comment by kurtxchen** [comment]
2014/01/22 14:05:31 ERROR - jmeter.protocol.amf.util.AmfXmlConverter: An exception was encountered while deserializing response.  flex.messaging.io.UnknownTypeException: Unknown AMF type '-65'.
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:225)
    at flex.messaging.io.amf.Amf0Input.readObject(Amf0Input.java:95)
    at flex.messaging.io.amf.AmfMessageDeserializer.readObject(AmfMessageDeserializer.java:226)
    at flex.messaging.io.amf.AmfMessageDeserializer.readBody(AmfMessageDeserializer.java:205)
    at flex.messaging.io.amf.AmfMessageDeserializer.readMessage(AmfMessageDeserializer.java:125)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:168)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:140)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.populateSampler(AmfRequestHdr.java:463)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.getSampler(AmfRequestHdr.java:281)
    at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:224)
