### ISSUE TITLE
problem with DSC in ClassAliasRegistry

### ISSUE THREAD

**Issue by winko** [sharp-bits/jmeter-amf#32]
The code and comments in file AmfXmlConverter.java beginning with row 145 says:

```
// Class aliases for deserialization, mimics registerClassAlias in Flex
//   Generally only used in rendering as it can cause serious problems for proxy sampling
if (useAliasRegistry) {
    ClassAliasRegistry aliases = ClassAliasRegistry.getRegistry();
    aliases.registerAlias("DSC", "flex.messaging.messages.CommandMessageExt"); // This causes errors in XStream during proxy sampling (cannot cast byte to string)
    aliases.registerAlias("DSK", "flex.messaging.messages.AcknowledgeMessageExt");
}
```

When **useAliasRegistry** is **false** I got:
- ERROR - jmeter.protocol.amf.util.AmfXmlConverter: An exception was encountered while deserializing response. flex.messaging.MessageException: Cannot create class of type 'DSC'. Type 'DSC' not found.

When **useAliasRegistry** is **true** I got:
- com.thoughtworks.xstream.converters.ConversionException: java.lang.Byte cannot be cast to java.lang.String : java.lang.Byte cannot be cast to java.lang.String

Does anybody an idea how to solve this problem?

**Comment by noogrub** [comment]
Have a look here:
http://stackoverflow.com/questions/8654141/convert-byte-to-string-in-java

Sounds like maybe you need to add an encoding to get it to work?

On Wed, Mar 13, 2013 at 10:21 AM, winko notifications@github.com wrote:

> The code and comments in file AmfXmlConverter.java beginning with row 145
> says:
> 
> // Class aliases for deserialization, mimics registerClassAlias in Flex
> //   Generally only used in rendering as it can cause serious problems for proxy sampling
> if (useAliasRegistry) {
>     ClassAliasRegistry aliases = ClassAliasRegistry.getRegistry();
>     aliases.registerAlias("DSC", "flex.messaging.messages.CommandMessageExt"); // This causes errors in XStream during proxy sampling (cannot cast byte to string)
>     aliases.registerAlias("DSK", "flex.messaging.messages.AcknowledgeMessageExt");
> }
> 
> When _useAliasRegistry_ is _false_ I got:
> - ERROR - jmeter.protocol.amf.util.AmfXmlConverter: An exception was
>   encountered while deserializing response. flex.messaging.MessageException:
>   Cannot create class of type 'DSC'. Type 'DSC' not found.
> 
> When _useAliasRegistry_ is _true_ I got:
> - com.thoughtworks.xstream.converters.ConversionException:
>   java.lang.Byte cannot be cast to java.lang.String : java.lang.Byte cannot
>   be cast to java.lang.String
> 
> Does anybody an idea how to solve this problem?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/steeltomato/jmeter-amf/issues/32
> .

## 

John Burgoon
Software engineer/application developer
Herff Jones, Inc.
_-- "__Time flies, but as I get older it seems like the landings are
getting a little rough.__"_

**Comment by winko** [comment]
That's an idea...  I will look for this...

For information I will attach all the debugging information below.

I'm wondering if it is possible (and reasonable) to force an encoding by the _fromXML_ method of XStream... ?

## 

com.thoughtworks.xstream.converters.ConversionException: java.lang.Byte cannot be cast to java.lang.String : java.lang.Byte cannot be cast to java.lang.String
---- Debugging information ----
message : java.lang.Byte cannot be cast to java.lang.String
cause-exception : java.lang.ClassCastException
cause-message : java.lang.Byte cannot be cast to java.lang.String
class : flex.messaging.messages.CommandMessageExt
required-type : flex.messaging.messages.CommandMessageExt
converter-type : com.thoughtworks.xstream.converters.reflection.ExternalizableConverter
path : /ActionMessage/bodies/MessageBody/data/DSC
line number : 11
class[1] : [Ljava.lang.Object;
converter-type[1] : com.thoughtworks.xstream.converters.collections.ArrayConverter
class[2] : flex.messaging.io.amf.MessageBody
converter-type[2] : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[3] : java.util.ArrayList
converter-type[3] : com.thoughtworks.xstream.converters.collections.CollectionConverter
class[4] : flex.messaging.io.amf.ActionMessage
version : null

---

at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:71)
at com.thoughtworks.xstream.converters.collections.ArrayConverter.unmarshal(ArrayConverter.java:55)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:355)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:306)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:234)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:71)
at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:79)
at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:72)
at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:66)
at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:61)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:355)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:306)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:234)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1052)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1036)
at com.thoughtworks.xstream.XStream.fromXML(XStream.java:912)
at com.thoughtworks.xstream.XStream.fromXML(XStream.java:903)
at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertXmlToAmfMessage(AmfXmlConverter.java:119)
at org.apache.jmeter.protocol.amf.sampler.AmfRequest.sample(AmfRequest.java:158)
at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1088)
at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:255)
Caused by: java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.String
at flex.messaging.messages.AbstractMessage.readExternal(AbstractMessage.java:248)
at flex.messaging.messages.AsyncMessage.readExternal(AsyncMessage.java:98)
at flex.messaging.messages.CommandMessage.readExternal(CommandMessage.java:296)
at com.thoughtworks.xstream.converters.reflection.ExternalizableConverter.unmarshal(ExternalizableConverter.java:135)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
... 40 more

**Comment by noogrub** [comment]
The part I don't know is whether it's possible to simply provide an
additional argument for encoding in XStream.  Seems like the elegant,
environment-independent solution if so.

**Comment by winko** [comment]
Yes, this would be great....

On the other hand:
I am starting the JVM for JMeter with the argument **-Dfile.encoding=ISO-8859-1**. Since it is recommended to use the UTF-8 encoding format in Flex (http://www.adobe.com/support/documentation/en/flex/1/internationalization_flex_short/internationalization_flex_short9.html ) I have tried to change the argument to **-Dfile.encoding=UTF-8** but then I get another error:

ERROR - jmeter.protocol.amf.util.AmfXmlConverter: An exception was encountered while deserializing response.  flex.messaging.io.UnknownTypeException: Unknown AMF type '-65'.
    at flex.messaging.io.amf.Amf0Input.readObjectValue(Amf0Input.java:225)
    at flex.messaging.io.amf.Amf0Input.readObject(Amf0Input.java:95)
    at flex.messaging.io.amf.AmfMessageDeserializer.readObject(AmfMessageDeserializer.java:226)
    at flex.messaging.io.amf.AmfMessageDeserializer.readBody(AmfMessageDeserializer.java:205)
    at flex.messaging.io.amf.AmfMessageDeserializer.readMessage(AmfMessageDeserializer.java:125)
    at org.apache.jmeter.protocol.amf.util.AmfXmlConverter.convertAmfMessageToXml(AmfXmlConverter.java:169)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.populateSampler(AmfRequestHdr.java:465)
    at org.apache.jmeter.protocol.amf.proxy.AmfRequestHdr.getSampler(AmfRequestHdr.java:281)
    at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:224)

This one was already reported within one another issue here.
