### ISSUE TITLE
Errors with JMeter 3+

### ISSUE THREAD

**Issue by IXEguy** [sharp-bits/jmeter-amf#39]
I'm currently trying with JMeter 3.1, but I think I remember seeing it with 3 as well when it first came out.

I know not many people use this anymore, but looking for some suggestions from someone who is familiar with the plugin on where & what to look at to get started at getting this to work with JMeter 3.

```
2017/01/16 08:30:57 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: org/htmlparser/util/ParserException
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.addFormEncodings(AmfProxy.java:573)
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:275)
Caused by: java.lang.ClassNotFoundException: org.htmlparser.util.ParserException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

2017/01/16 08:30:57 INFO  - jmeter.protocol.http.sampler.HTTPHC4Impl: HTTP request retry count = 0 
2017/01/16 08:30:59 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: org/htmlparser/util/ParserException
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.addFormEncodings(AmfProxy.java:573)
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:275)
Caused by: java.lang.ClassNotFoundException: org.htmlparser.util.ParserException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

2017/01/16 08:31:00 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: org/htmlparser/util/ParserException
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.addFormEncodings(AmfProxy.java:573)
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:275)
Caused by: java.lang.ClassNotFoundException: org.htmlparser.util.ParserException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

2017/01/16 08:31:00 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: org/htmlparser/util/ParserException
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.addFormEncodings(AmfProxy.java:573)
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:275)
Caused by: java.lang.ClassNotFoundException: org.htmlparser.util.ParserException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

2017/01/16 08:31:01 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: org/htmlparser/util/ParserException
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.addFormEncodings(AmfProxy.java:573)
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:275)
Caused by: java.lang.ClassNotFoundException: org.htmlparser.util.ParserException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

2017/01/16 08:31:02 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: org/htmlparser/util/ParserException
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.addFormEncodings(AmfProxy.java:573)
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:275)
Caused by: java.lang.ClassNotFoundException: org.htmlparser.util.ParserException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

2017/01/16 08:31:03 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: org/htmlparser/util/ParserException
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.addFormEncodings(AmfProxy.java:573)
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:275)
Caused by: java.lang.ClassNotFoundException: org.htmlparser.util.ParserException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

2017/01/16 08:31:04 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: org/htmlparser/util/ParserException
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.addFormEncodings(AmfProxy.java:573)
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:275)
Caused by: java.lang.ClassNotFoundException: org.htmlparser.util.ParserException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

2017/01/16 08:31:05 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: org/htmlparser/util/ParserException
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.addFormEncodings(AmfProxy.java:573)
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:275)
Caused by: java.lang.ClassNotFoundException: org.htmlparser.util.ParserException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

2017/01/16 08:31:06 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: org/htmlparser/util/ParserException
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.addFormEncodings(AmfProxy.java:573)
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:275)
Caused by: java.lang.ClassNotFoundException: org.htmlparser.util.ParserException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more
```
Beyond recording & load testing, my expertise with this plugin thus far has only been looking at the additions that others have made on github & compiling a 1.6 version out of that.

**Comment by IXEguy** [comment]
I got around most of the errors by adding these 2 jars to the lib folder of the jmeter 3.1 instance:
```
htmllexer-2.1.jar
htmlparser-2.1.jar
```
(I think htmlparser is also in htmllexer)

They were already in the source that I had used to build the jmeter-amf jar.

Still got a few issues to work through, will try and update if I needed to do anything else to get it working.

**Comment by IXEguy** [comment]
Abandoned working with 3.x and stuck with 2.13, so did not do any additional work on this.
