### ISSUE TITLE
Please provide the JMetre-AMF jar

### ISSUE THREAD

**Issue by chinni20** [sharp-bits/jmeter-amf#40]
Hi,  

I have tried in both ways by cloneing the project as well as by downloading the ZIP folder, but neither  I did not find lib folder not JMeter- AMF.jar file in the entire ZIP folder.

Could some one please  provide JMeter- AMF.jar file and BladeZS jar files.

-Chinni20

**Comment by IXEguy** [comment]
If you clone/download the project, you have to build it, else it is in [downloads](https://github.com/steeltomato/jmeter-amf/downloads).

Please use with 2.13, you will have to make additional modifications to source to get this to work with 3.x (refer to #39 )

Adobe turned over Flex to the Apache foundation, for any downloads refer to their [site](https://flex.apache.org) now. BlazeDS in particular is now [here](https://flex.apache.org/download-blazeds.html).

**Comment by chinni20** [comment]
@IXEguy ,

Thanks for the AMF package  as well as BlazeDS file link!
 As instructed in the Userguide i have kept the Blazed DS as well as AMF jar under  lib/ext as soon i Start the AMF Proxy getting the below error  and doesnot launch the application. Note : By default AMF proxt is 8080, but as per userguide instructions  my PC proxy settings are 127.0.0.1  and port is 8888, so i have set port AMF proxy as 8888. The moment started recording the application  , getting the below error.

Please advise how to over come the below issue.

2018-03-11 15:42:18,456 INFO o.a.j.p.h.p.ProxyControl: HTTP(S) Test Script Recorder SSL Proxy will use keys that support embedded 3rd party resources in file C:\JMETER\apache-jmeter-3.3\bin\proxyserver.jks
2018-03-11 15:42:18,591 INFO o.a.j.g.u.MenuFactory: Skipping org.apache.jmeter.protocol.java.sampler.BSFSampler
2018-03-11 15:42:18,622 INFO o.a.j.s.FileServer: Default base='C:\JMETER\apache-jmeter-3.3\bin'
2018-03-11 15:42:18,669 INFO o.a.j.g.u.MenuFactory: Skipping org.apache.jmeter.protocol.mongodb.config.MongoSourceElement
2018-03-11 15:42:18,669 INFO o.a.j.g.u.MenuFactory: Skipping org.apache.jmeter.protocol.mongodb.sampler.MongoScriptSampler
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_qos]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_at_most_once]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_at_least_once]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_exactly_once]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_client_types]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_blocking_client]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_async_client]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_message_input_type]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_message_input_type_text]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_message_input_type_file]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_qos]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_at_most_once]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_at_least_once]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_exactly_once]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_client_types]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_blocking_client]
2018-03-11 15:42:18,669 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [mqtt_async_client]
2018-03-11 15:42:19,013 INFO o.a.j.g.u.MenuFactory: Skipping org.apache.jmeter.timers.BSFTimer
2018-03-11 15:42:19,029 INFO o.a.j.g.u.MenuFactory: Skipping org.apache.jmeter.visualizers.BSFListener
2018-03-11 15:42:52,811 INFO o.a.j.p.h.c.CookieManager: Settings: Delete null: true Check: true Allow variable: true Save: false Prefix: COOKIE_
2018-03-11 15:43:15,779 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [proxy_httpsspoofing]
2018-03-11 15:43:15,795 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [proxy_httpsspoofing_match]
2018-03-11 15:43:48,717 INFO o.a.j.p.a.p.AmfDaemon: Creating Daemon Socket on port: 8888
2018-03-11 15:43:48,717 INFO o.a.j.p.a.p.AmfDaemon: Proxy up and running!
2018-03-11 15:43:51,102 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.NoClassDefFoundError: org/apache/jmeter/protocol/http/sampler/HTTPSampler2
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_152]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_152]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_152]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_152]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_152]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_152]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_152]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_152]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_152]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_152]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_152]
	at org.apache.jmeter.protocol.amf.proxy.AmfDaemon.run(AmfDaemon.java:125) ~[JMeter-AMF.jar:?]
Caused by: java.lang.ClassNotFoundException: org.apache.jmeter.protocol.http.sampler.HTTPSampler2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
	... 16 more
2018-03-11 15:47:20,068 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [proxy_httpsspoofing]
2018-03-11 15:47:20,068 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [proxy_httpsspoofing_match]
2018-03-11 15:47:26,001 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [proxy_httpsspoofing]
2018-03-11 15:47:26,001 WARN o.a.j.u.JMeterUtils: ERROR! Resource string not found: [proxy_httpsspoofing_match]
2018-03-11 15:47:29,372 INFO o.a.j.p.a.p.AmfDaemon: Creating Daemon Socket on port: 8080
2018-03-11 15:47:29,387 INFO o.a.j.p.a.p.AmfDaemon: Proxy up and running!
2018-03-11 15:48:01,181 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.NoClassDefFoundError: org/apache/jmeter/protocol/http/sampler/HTTPSampler2
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_152]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_152]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_152]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_152]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_152]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_152]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_152]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_152]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_152]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_152]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_152]
	at org.apache.jmeter.protocol.amf.proxy.AmfDaemon.run(AmfDaemon.java:125) ~[JMeter-AMF.jar:?]
Caused by: java.lang.ClassNotFoundException: org.apache.jmeter.protocol.http.sampler.HTTPSampler2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
	... 16 more

**Comment by IXEguy** [comment]
Try it with JMeter 2.13, I could not get this plugin working even after
modifying the AMF plugin with JMeter 3+.

**Comment by chinni20** [comment]
@IXEguy , No  luck getting the Null Pointer Exception.

2018/03/12 19:26:58 INFO  - jmeter.util.JMeterUtils: Setting Locale to en_US 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: Loading user properties from: C:\JMETER\apache-jmeter-2.13\bin\user.properties 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: Loading system properties from: C:\JMETER\apache-jmeter-2.13\bin\system.properties 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: Copyright (c) 1998-2015 The Apache Software Foundation 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: Version 2.13 r1665067 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: java.version=1.8.0_152 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: java.vm.name=Java HotSpot(TM) 64-Bit Server VM 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: os.name=Windows 10 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: os.arch=amd64 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: os.version=10.0 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: file.encoding=Cp1252 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: Default Locale=English (United States) 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: JMeter  Locale=English (United States) 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: JMeterHome=C:\JMETER\apache-jmeter-2.13 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: user.dir  =C:\JMETER\apache-jmeter-2.13\bin 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: PWD       =C:\JMETER\apache-jmeter-2.13\bin 
2018/03/12 19:26:58 INFO  - jmeter.JMeter: IP: xxxx.xx.xx.xxx Name: xxxxx FullName: xxxx.xxx.xxxx
2018/03/12 19:26:59 INFO  - jmeter.gui.action.LookAndFeelCommand: Using look and feel: javax.swing.plaf.metal.MetalLookAndFeel [Metal, CrossPlatform] 
2018/03/12 19:26:59 INFO  - jmeter.JMeter: Loaded icon properties from org/apache/jmeter/images/icon.properties 
2018/03/12 19:26:59 INFO  - jmeter.engine.util.CompoundVariable: Note: Function class names must contain the string: '.functions.' 
2018/03/12 19:26:59 INFO  - jmeter.engine.util.CompoundVariable: Note: Function class names must not contain the string: '.gui.' 
2018/03/12 19:26:59 INFO  - jmeter.util.BSFTestElement: Registering JMeter version of JavaScript engine as work-round for BSF-22 
2018/03/12 19:27:00 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [proxy_httpsspoofing] 
2018/03/12 19:27:00 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [proxy_httpsspoofing_match] 
2018/03/12 19:27:00 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Cannot find .className property for htmlParser, using default 
2018/03/12 19:27:00 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/html is  
2018/03/12 19:27:00 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xhtml+xml is  
2018/03/12 19:27:00 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xml is  
2018/03/12 19:27:00 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/xml is  
2018/03/12 19:27:00 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser 
2018/03/12 19:27:00 INFO  - jmeter.gui.util.MenuFactory: Skipping org.apache.jmeter.protocol.http.control.gui.WebServiceSamplerGui 
2018/03/12 19:27:00 INFO  - jmeter.gui.util.MenuFactory: Skipping org.apache.jmeter.protocol.http.modifier.gui.ParamModifierGui 
2018/03/12 19:27:00 INFO  - jorphan.exec.KeyToolUtils: keytool found at 'keytool' 
2018/03/12 19:27:00 INFO  - jmeter.protocol.http.proxy.ProxyControl: HTTP(S) Test Script Recorder SSL Proxy will use keys that support embedded 3rd party resources in file C:\JMETER\apache-jmeter-2.13\bin\proxyserver.jks 
2018/03/12 19:27:01 INFO  - jmeter.samplers.SampleResult: Note: Sample TimeStamps are START times 
2018/03/12 19:27:01 INFO  - jmeter.samplers.SampleResult: sampleresult.default.encoding is set to ISO-8859-1 
2018/03/12 19:27:01 INFO  - jmeter.samplers.SampleResult: sampleresult.useNanoTime=true 
2018/03/12 19:27:01 INFO  - jmeter.samplers.SampleResult: sampleresult.nanoThreadSleep=5000 
2018/03/12 19:27:23 INFO  - jmeter.protocol.http.control.CookieManager: Settings: Delete null: true Check: true Allow variable: true Save: false Prefix: COOKIE_ 
2018/03/12 19:27:47 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [proxy_httpsspoofing] 
2018/03/12 19:27:47 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [proxy_httpsspoofing_match] 
2018/03/12 19:27:54 INFO  - jmeter.protocol.amf.proxy.AmfDaemon: Creating Daemon Socket on port: 8080 
2018/03/12 19:27:54 INFO  - jmeter.protocol.amf.proxy.AmfDaemon: Proxy up and running! 
2018/03/12 19:28:06 INFO  - jmeter.protocol.amf.proxy.AmfProxy: Proxy will remove the headers: If-Modified-Since,If-None-Match,Host 
2018/03/12 19:28:06 INFO  - jmeter.protocol.http.sampler.HTTPHCAbstractImpl: Local host = xxxx
2018/03/12 19:28:06 INFO  - jmeter.protocol.http.sampler.HTTPHC3Impl: HTTP request retry count = 0 
2018/03/12 19:28:06 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NullPointerException
	at org.apache.jmeter.protocol.amf.proxy.AmfProxyControl.deliverSampler(AmfProxyControl.java:433)
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:315)

2018/03/12 19:28:11 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NullPointerException
	at org.apache.jmeter.protocol.amf.proxy.AmfProxyControl.deliverSampler(AmfProxyControl.java:433)
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:315)

2018/03/12 19:28:13 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NullPointerException
	at org.apache.jmeter.protocol.amf.proxy.AmfProxyControl.deliverSampler(AmfProxyControl.java:433)
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:315)

2018/03/12 19:28:41 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NullPointerException
	at org.apache.jmeter.protocol.amf.proxy.AmfProxyControl.deliverSampler(AmfProxyControl.java:433)
	at org.apache.jmeter.protocol.amf.proxy.AmfProxy.run(AmfProxy.java:315)

**Comment by IXEguy** [comment]
Sorry, no idea what's causing that error.
